### ISSUE TITLE
Start working on github wiki

### ISSUE THREAD

**Issue by marco-ponds** [MageStudio/Mage#16]

**Comment by TheCodeCrafter** [comment]
Hey, can I get this done, I am pretty good at writing (and even managing forums too, 💯 !) Wikis for engines (considering the fact that I am an abstract back-end programmer. I do need to do some research on Mage, so let me in on some stuff!

P.S. If you have a specific website to make it on, lemme know!

**Comment by ryker-s** [comment]
I've been reading the documentation and I gotta say I absolutely LOVE the cleanness of the scripting API. Great work! @marco-ponds

**Comment by marco-ponds** [comment]
Documentation is currently published here https://magestudio.github.io/mage-docs/#/ . This issue can now be closed
