### ISSUE TITLE
New comer friendly

### ISSUE THREAD

**Issue by ryker-s** [MageStudio/Mage#76]
Any chance to have a getting started part of readme?

**Comment by marco-ponds** [comment]
Hi! Yes, I do have a task for me to create a getting started documentation, but I always end up focusing on different things, due to the lack of  "users" . I will definitely prioritise that now. Sorry for the terrible delay (more than a month).

**Comment by marco-ponds** [comment]
@ryker-s It's been a while, but I finally had the chance to start working on a proper documentation. The preliminary version is currently hosted here https://magestudio.github.io/mage-docs/#/ , and I'm going to spend this week on finishing up the Getting Started section as well as some more in-depth sections.  Feel free to start having a look, if you find something that doesn't look right, don't hesitate to let me know.

**Comment by marco-ponds** [comment]
This can be closed, the getting started guide is now available.
