### ISSUE TITLE
Add Terrain-slope collision / camera follow collision?

### ISSUE THREAD

**Issue by Thundros** [MageStudio/Mage#83]
Hi @marco-ponds ! First off I'd like to say. GOOD JOB on MAGE! I absolutely LOVE it! PLEASE keep up the good work! <3

Second, I would like to ask that you add Terrain-slope collision with the ability to change the X-angle to simulate the steepness in which the player slides down the Terrain slope. Also, I would like to ask that you add a camera that smoothly follows the player with collision.

Once again, PLEASE keep up the GREAT work! and I would like to beta test this new functionality too if at all possible!

**Comment by Thundros** [comment]
@marco-ponds Hello?

**Comment by marco-ponds** [comment]
Hello @Thundros ! Sorry for the late reply, I'm so used of writing my own issues, I tend to not notice issues raised by someone else. 😄 I really like that proposal, and I had plans to work on something similar in the near future. I will keep you posted.

**Comment by Thundros** [comment]
@marco-ponds : HOW LONG?! I WOULD BE HONORED TO BETA TEST IT!

**Comment by marco-ponds** [comment]
@Thundros I don't have a timeline for this one, but I suspect I can work on it in the coming weeks 🤔 i have a task for this on my board. I'll let you know when you can test it

**Comment by Thundros** [comment]
@marco-ponds Please do let me know! <3

**Comment by Thundros** [comment]
@marco-ponds : Any luck with Terrain - slope / camera follow collision?

**Comment by Thundros** [comment]
@marco-ponds : hello?

**Comment by marco-ponds** [comment]
Hey @Thundros ! Sorry, I've been particularly busy at work, and I've been also working on something different for Mage, which is enabling the Physics engine to run in a WebWorker. Now, here is something I can do: at the moment the documentation is not exactly great, I had the plan to work on it anyway during the weekend. Do you think that with a "proper" documentation you would be able to open a PR? I'm going to add a set of builtin scripts to the ScriptsEngine, I believe you could add a slope/camera follow script to that.

**Comment by Thundros** [comment]
@marco-ponds : I am not sure how to do it or I wouldn't be asking. LOL! :P

**Comment by Thundros** [comment]
@marco-ponds : hello?

**Comment by Thundros** [comment]
@marco-ponds : Are you there?

**Comment by Thundros** [comment]
@marco-ponds : Hello?

**Comment by ryker-s** [comment]
@Thundros It will be added when the time is right either by Marco or the community 👍 .

**Comment by Thundros** [comment]
Can't WAIT to see this feature! <3 I ALREADY LOVE M.A.G.E.! <3
